### ISSUE TITLE
Use voxel2mesh in another dataset, continuing #11 

### ISSUE THREAD

**Issue by afoix** [cvlab-epfl/voxel2mesh#12]
The initial issue was #11 I am reopening an issue for further clarification if that's OK, @udaranga3001  😊 

Thank you for confirming the structure of the code. Now, what is left as a question mark is the way one goes about implementing the pre_process_dataset method. Given the currently available resources I found in the repo, I would have to already be familiar with the structure of the Chaos dataset or of the Hippocampus dataset to have a shot at then understanding what it is that they do in their implementation of the pre_process_dataset method, hope that this clarifies the structure of the pickle file, and only then be able to start trying to populate a pickle file for an arbitrary other dataset. This is what I would like to avoid. One helpful step here would be a more readily accessible piece of documentation describing the expected format of the pickle file (its byte structure).

Hopefully you can provide some clarifications along these lines?

Thank you again for your help

**Comment by udaranga3001** [comment]
Hi,

The question is not very clear to me. Basically, the pre_process_dataset function, loads images and ground truth, store in Sample objects, and finally save the whole set in a pickle file. You don't have to worry about the bite structure of the pickle file. Pickle library takes care of it. You just need to create the list of Sample objects. Then when you run the experiments, quick_load will load the pickle file and use the data.
