### ISSUE TITLE
RuntimeError:No surface found at the given iso value.

### ISSUE THREAD

**Issue by Halleyawoo** [cvlab-epfl/voxel2mesh#13]
Hello, thank you very much for your work. I encountered an error during the evaluation process while using my own dataset (in nii.gz format). When I printed the matrix, I found that it was all zeros. I haven't been able to identify the problem yet. Would you be able to assist me with this issue? Thank you.
￼￼

**Comment by Halleyawoo** [comment]
![20230413180619](https://user-images.githubusercontent.com/46990176/231727039-ffd95922-ac29-4c4e-9dba-f6138d9752b2.jpg)
![20230413180724](https://user-images.githubusercontent.com/46990176/231727048-f052cfb4-5b15-4c68-830e-d7d5c7d3008d.jpg)

**Comment by udaranga3001** [comment]
I assume this volume is coming from your ground truth annotation. If that's the case, I think there is an issue with your data loader. It's not loading the annotations properly, instead, it simply outputs a zero tensor.
