### ISSUE TITLE
Comparative Experiment

### ISSUE THREAD

**Issue by cong-code** [cvlab-epfl/voxel2mesh#17]
Hello, author, I would like to inquire about the Pixel2Mesh-3D mentioned in your comparison experiment, whether you can provide this part of the code. My email address is 2312930648@qq.com. I would appreciate it if you could help me, best wishes to you.

**Comment by udaranga3001** [comment]
Unfortunately, I don't plan to update the repo again. 
But, you should be able to get Pixel2Mesh-3D by updating the Voxel2Mesh model class. For example, you have to sample features from Voxel encoder instead of the decoder, changing the sampling function, etc.
