### ISSUE TITLE
How to run model with Hippocampus dataset?

### ISSUE THREAD

**Issue by Dr2n** [cvlab-epfl/voxel2mesh#2]
Hi,

This looks like interesting work! Could you provide instructions on how the code in this repository can be modified to work with the Hippocampus dataset?

The code in `main.py` appears to run `Chaos()` on line 73, which then tries to preprocess DICOM files from the chaos dataset.

It would be wonderful to try Voxel2Mesh on the Hippocampus dataset or other .nii files.

Thank you!

**Comment by udaranga3001** [comment]
Hi, 

I have added the data loader for the Hippocampus dataset. You can try it now and let me know if there is an issue. Note that I updated the data pre-processing part as well to simplify the execution. Please read the steps in **Running experiments**.

**Comment by smallmax00** [comment]
Hi, it seems that hippocampus.py ->pre_process_dataset function load .npy data instead of .nii.gz, should we convert the dataset into npy before running the data_preprocessing.py?
