### ISSUE TITLE
Data preprocessing for CHAOS dataset can break.

### ISSUE THREAD

**Issue by patmjen** [cvlab-epfl/voxel2mesh#3]
First, thanks a lot for releasing the code!

During preprocessing of the CHAOS dataset, the xy-slices may get loaded out-of-order since `os.listdir` does not necessarily sort the file names. Specifically, L104 and L152 in `data/chaos.py`:
https://github.com/cvlab-epfl/voxel2mesh/blob/050a851baad12014e30b9ae93ca1f3d887132bf2/data/chaos.py#L104
https://github.com/cvlab-epfl/voxel2mesh/blob/050a851baad12014e30b9ae93ca1f3d887132bf2/data/chaos.py#L152

This messes up the data since the xy-slices are then in the wrong order. Calling `sorted` on `images_path` seems to fix it.

**Comment by udaranga3001** [comment]
I agree that this can cause an issue. Thank you for pointing it out. I will update the code. 

In our experiments, it didn't cause any problems. If it did, we would have noticed it since we save image volumes and ground truth volumes in the experiments.

**Comment by patmjen** [comment]
Great, thank you!
Just to be clear, the reason for my issue was that I did run the code and had this exact issue.

**Comment by Polaris112027** [comment]
So, the solution to this problem is still not updated in the code. Can you post the exact code for your solution? I also encountered this problem

**Comment by patmjen** [comment]
Sure, I changed it to
```
images_path = [dir for dir in os.listdir('{}/{}/DICOM_anon'.format(data_root, sample)) if 'dcm' in dir]
images_path = sorted(images_path)
```
at L104, and 
```
images_path = [dir for dir in os.listdir('{}/{}/DICOM_anon'.format(data_root, sample)) if 'png' in dir]
images_path = sorted(images_path)
```
at L152.

This sorts the images by name, which puts them in the correct order.

**Comment by Polaris112027** [comment]
I run the code but meet the error:No such file or directory: '/content/drive/My Drive/voxel2mesh/Chaos/Train_Sets/DICOM_anon' . I checked the path but found that the correct format of path should be like "voxel2mesh/Chaos/Train_Sets/CT(or MR)/1(or 2,3,4...)/DICOM_anon" .Have you ever met the same error?Do you have any suggestion to deal with this error?
