### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sky4689524** [cvlab-epfl/voxel2mesh#4]
Hello,

I am trying to implement Voxel2Mesh with Hippocampus dataset.

Firstly, I want to execute data_proprocess.py.

But I have this error.

```
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/rasterize_cuda/build.ninja...
Building extension module rasterize_cuda...
ninja: no work to do.
Loading extension module rasterize_cuda...
Traceback (most recent call last):
  File "data_preprocess.py", line 24, in <module>
    from model.voxel2mesh import Voxel2Mesh as network
  File "/home/hanwool/git/voxel2mesh/model/voxel2mesh.py", line 6, in <module>
    from pytorch3d.ops import sample_points_from_meshes
  File "/home/hanwool/.local/lib/python3.6/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/hanwool/.local/lib/python3.6/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

```

I use Pytorch version 1.4.0, CUDA 10.1 and Python version: 3.6.
I use pytorch3d 0.2.0 version.

Do you know why this error occurs?

**Comment by udaranga3001** [comment]
Hi,

No, I don't get this error. I use
Pytorch 1.4.0, CUDA 10.2, python 3.6.9 and pytorch3d 0.1.1

But I did a quick google search and people seem to report this error arising due to compatibility issues between pytorch and pytorch3d. May be you need to update one. 

If you find a solution, let me know.

**Comment by sky4689524** [comment]
Hi,

Thank you for answering.

I reinstalled pytorch3d 0.1.1 version. After then, this error does not happen anymore.
